apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-nodeport
  namespace: simple-node-app
spec:
  type: NodePort
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 3000 # Port the service is listening on
      targetPort: 3000 # Port the container is listening on (if unset, defaults to equal port value)
      # nodePort: 30XXX (if unset, kubernetes will assign a port within 30000-32767)
