apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-lb
  namespace: simple-node-app
spec:
  type: LoadBalancer # Will only work if cluster is configured to provision one from an external source (e.g. cloud provider)
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 3000 # Port the container is listening on (if unset, defaults to equal port value)
